  _BASE_CONFIG_ : ./configs/base/levir.yml
  mode : test
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: New3
  logfilepath: logs/new3_levir/new3_levir.log
  train:
    epochs : 100
    batch_size : 6
    snapshots_dir : ./checkpoints/New3_model/
    save_intervals : 5
  eval :
    batch_size : 6
  test:
    batch_size : 6
    checkpoint : checkpoints/New3_model/New3_best.ckpt
    save_path : ./results/New3/levir-cd/
  model:
      output_channels: 1
      type : new3net
  losses: 
          loss_cls: 
              type: BCELoss
  scheduler: 
        type : PolynomialDecayLR
        learning_rate: 0.001
        end_learning_rate: 0.0005
        decay_steps: 4
        power: 0.5
  optimizer:  
        type: Adam
        momentum: 0.9
        weight_decay: 0.0005

  
      
        