  _BASE_CONFIG_ : ./configs/base/levir.yml
  mode : train
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: New2
  logfilepath: logs/new2_levir/new2_levir.log
  train:
    epochs : 100
    batch_size : 6
    snapshots_dir : ./checkpoints/New2_model/
    save_intervals : 5
  eval :
    batch_size : 6
  test:
    batch_size : 6ss
    checkpoint : checkpoints/New2_model/New2_best.ckpt
    save_path : ./results/New2/levir-cd/
  model:
      output_channels: 1
      type : New2Net
  losses: 
          loss_cls: 
              type: BCELoss
  scheduler: 
        type : PolynomialDecayLR
        learning_rate: 0.001
        end_learning_rate: 0.0005
        decay_steps: 4
        power: 0.5
  optimizer:  
        type: Adam
        momentum: 0.9
        weight_decay: 0.0005

  
      
        