  _BASE_CONFIG_ : ./configs/base/levir.yml
  mode : train
  device : GPU
  type : BinaryChangeDetectionFramework
  model_name: FDCNN
  logfilepath: logs/fdcnn_levir/fdcnn_levir.log
  train:
    epochs : 100
    batch_size : 2
    snapshots_dir : ./checkpoints/FDCNN/
    save_intervals : 10
  eval :
    batch_size : 10
  test:
    batch_size : 10
    checkpoint : /root/autodl-tmp/LuoJiaChangeDetection-master/checkpoints/FDCNN/FDCNN_1-100_712.ckpt
    save_path : ./results/FDCNN/levir-cd/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: VggEncoder
    decode_head : 
      type: FDCNNDecoder
      n_class: 1
      filters: [64,128,256,512]
    feature_interaction: 
      type: normal
      policy: abs_diff
      out_indices: [0,1,2,3]
    prediction_head:
      type: FCNHead
      in_channels: 64
  losses: 
          loss_cls: 
              type: BCELoss
  scheduler: 
        type : PolynomialDecayLR
        learning_rate: 0.001
        end_learning_rate: 0.0005
        decay_steps: 4
        power: 0.5
  optimizer:  
        type: Adam
        weight_decay: 0.0005

  
      
        