     dataset:
        type: OSCDDataset
        rootdir: /media/lscsc/nas/xianping/ZXK/CDDemo/CDFramework/data/OSCD-samples
        img_folder_names: 
              - 'imgs_1_rect'
              - 'imgs_2_rect'
              - 'transformed1'
              - 'transformed2'
              - 'cm'
