  _BASE_CONFIG_ : ./configs/base/gvlm.yml
  mode : train
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: BiT
  logfilepath: logs/bit_gvlm/bit_gvlm.log
  train:
    epochs : 100
    batch_size : 10
    snapshots_dir : ./checkpoints/
    save_intervals : 10
  eval :
    batch_size : 10
  test:
    batch_size : 10
    checkpoint : checkpoints/BiT/20.pth
    save_path : ./results/BiT/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: ResNetEncoder
    decode_head : 
      type: BITTrans
    feature_interaction: 
    prediction_head:
      type: FCNHead
      in_channels: 32
      output_channels: 1
  losses: 
          loss_cls: 
              type: BinaryCrossEntropyLoss
  scheduler: 
          type : ReduceLROnPlateau
          optimizer:  
                type: Adam
                lr: 0.001
                filter_params: True
                params_rules: {}

  
      
        