  _BASE_CONFIG_ : ./configs/base/levir.yml
  mode : test
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: TinyCD
  logfilepath: logs/tinycd_levir/tinycd_levir.log
  train:
    epochs : 100
    batch_size : 16
    snapshots_dir : ./checkpoints/
    save_intervals : 1
  eval :
    batch_size : 16
  test:
    batch_size : 16
    checkpoint : checkpoints/TinyCD/best_iou_levir.pth
    save_path : ./results/TinyCD/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: EfficientNetEncoder
    decode_head : 
      type: TinyCDDecoder
    feature_interaction: 
      type: MixingMaskAttentionInteraction
    prediction_head:
      type: FCNHead
      in_channels: 32
      output_channels: 1
  losses: 
          loss_cls: 
              type: BinaryCrossEntropyLoss
  scheduler: 
          type : ReduceLROnPlateau
          optimizer:  
                type: Adam
                lr: 0.001
                filter_params: True
                params_rules: {}

  
      
        