  _BASE_CONFIG_ : ./configs/base/gvlm.yml
  mode : train
  device : CPU
  type : BinaryChangeDetectionFramework
  model_name: ChangeFormer
  logfilepath: logs/changeformer_gvlm/changeformer_gvlm.log
  train:
    epochs : 100
    batch_size : 4
    snapshots_dir : ./checkpoints/ChangeFormer/
    save_intervals : 5
  eval :
    batch_size : 4
  test:
    batch_size : 4
    checkpoint : checkpoints/ChangeFormer/ChangeFormer_best.ckpt
    save_path : ./results/ChangeFormer/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: TransEncoder
      input_nc: 3
      output_nc: 1
      embedding_dim: 256
      embed_dims: [64, 128, 320, 512]
      depths: [3, 3, 4, 3]
    decode_head : 
      type: TransDecoder
      output_nc: 1
      embed_dims: [64, 128, 320, 512]
      depths: [3, 3, 4, 3]
      embedding_dim: 256
      decoder_softmax: False 
    feature_interaction: 
    prediction_head:
  losses: 
          loss_cls: 
              type: BCELoss
  scheduler: 
        type : PolynomialDecayLR
        learning_rate: 0.01
        end_learning_rate: 0.0005
        decay_steps: 4
        power: 0.5
  optimizer:  
        type: Adam
        momentum: 0.9
        weight_decay: 0.0005

  
      
        