  _BASE_CONFIG_ : ./configs/base/levir.yml
  mode : train
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: DSIFN
  logfilepath: logs/dsifn_levir/dsifn_levir.log
  train:
    epochs : 5
    batch_size : 4
    snapshots_dir : ./checkpoints/
    save_intervals : 5
  eval :
    batch_size : 10
  test:
    batch_size : 10
    checkpoint : checkpoints/DSIFN/10.pth
    save_path : ./results/DSIFN/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: VggEncoder

    decode_head : 
      type: CNNDecoderDeepSuper

    feature_interaction: 
      type: normal
      policy: concat
      out_indices: [0,1,2,3,4]
    prediction_head:

  losses: 
          loss_cls: 
              type: BinaryCrossEntropyLoss
  scheduler: 
          type : ReduceLROnPlateau
          optimizer:  
                type: Adam
                lr: 0.001
                filter_params: True
                params_rules: {}

  
      
        