  _BASE_CONFIG_ : ./configs/base/mcd.yml
  mode : test
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: USSFCNet
  logfilepath: logs/ussfcnet_mcd/ussfcnet_mcd.log
  train:
    epochs : 100
    batch_size : 36
    snapshots_dir : ./checkpoints/
    save_intervals : 10
  eval :
  test:
    batch_size : 20
    checkpoint : checkpoints/USSFCNet/100.pth
    save_path : ./results/USSFCNet/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: CNNAttentionEncoder
      in_ch: 3 
      mlp: [64,128,256,512,1024]
    decode_head : 
      type: CNNAttentionDecoder
      out_ch: 1
      mlp: [64,128,256,512,1024]
    feature_interaction: 
      type: normal
      policy: sum
      out_indices: [0,1,2,3,4]
    prediction_head:
      type: FCNHead
      in_channels: 32
      output_channels: 1
  losses: 
          loss_cls: 
              type: BinaryCrossEntropyLoss
  scheduler: 
          type : ReduceLROnPlateau
          optimizer:  
                type: Adam
                lr: 0.001
                filter_params: True
                params_rules: {}

  
      
        