  _BASE_CONFIG_ : ./configs/base/dsifn.yml
  mode : train
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: FC_Siam_diff
  logfilepath: logs/fc_siamdiff_dsifn/fc_siamdiff_dsifn.log
  train:
    epochs : 100
    batch_size : 16
    snapshots_dir : ./checkpoints/
    save_intervals : 1
  eval :
    batch_size : 16
  test:
    batch_size : 16
    checkpoint : checkpoints/FC_Siam_diff/30.pth
    save_path : ./results/FC_Siam_diff/landslide/
  model:
    CONNECTED: True
    CONNECTED_Temporal: T1T2
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: FCSiamEncoder
      in_channels: 3
      base_channel: 16
    decode_head : 
      type: FCSiamDecoder
      base_channel: 16
      mode : diff
    feature_interaction: 
      type: normal
      policy: diff
      out_indices: [0,1,2,3,4]
    prediction_head:
  losses: 
          loss_cls: 
              type: BinaryCrossEntropyLoss
  scheduler: 
          type : ReduceLROnPlateau
          optimizer:  
                type: Adam
                lr: 0.001
                filter_params: True
                params_rules: {}

  
      
        