  _BASE_CONFIG_ : ./configs/base/gvlm.yml
  mode : train
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: ICIFNet
  logfilepath: logs/icifnet_gvlm/icifnet_gvlm.log
  train:
    epochs : 100
    batch_size : 10
    snapshots_dir : ./checkpoints/
    save_intervals : 10
  eval :
    batch_size : 10
  test:
    batch_size : 10
    checkpoint : checkpoints/ICIFNet/10.pth
    save_path : ./results/ICIFNet/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: DualCNNandTransEncoder

    decode_head : 
      type: ICIFDecoder
      num_classes: 1
      # drop_rate: 0.2
      # conv: [64,64]
      # up: [64,128,256]
      # BasicConv2d: [1,128,320]
      # decode: [64,64]
    feature_interaction: 
      type: CrossAttentionInteraction
    prediction_head:


  losses: 
          loss_cls: 
              type: BinaryCrossEntropyLoss
  scheduler: 
          type : ReduceLROnPlateau
          optimizer:  
                type: Adam
                lr: 0.001
                filter_params: True
                params_rules: {}

  
      
        