  _BASE_CONFIG_ : ./configs/base/x2view.yml
  mode : train
  device : Ascend
  type : MulticlassChangeDetectionFramework
  model_name: TinyCD
  logfilepath: logs/tinycd_gvlm/tinycd_gvlm.log
  train:
    epochs : 100
    batch_size : 4
    snapshots_dir : ./checkpoints/TinyCD/
    save_intervals : 5
  eval :
    batch_size : 4
  test:
    batch_size : 4
    checkpoint : checkpoints/TinyCD/TinyCD-70_30.ckpt
    save_path : ./results/TinyCD/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 5
    backbone : 
      type: EfficientNetEncoder
    decode_head : 
      type: TinyCDDecoder
    feature_interaction: 
      type: MixingMaskAttentionInteraction
    prediction_head:
      type: FCNHead
      in_channels: 32
      output_channels: 5
  losses: 
          loss_cls: 
              type: CrossEntropyLoss
  scheduler: 
        type : PolynomialDecayLR
        learning_rate: 0.01
        end_learning_rate: 0.0005
        decay_steps: 4
        power: 0.5
  optimizer:  
        type: Adam
        momentum: 0.9
        weight_decay: 0.0005

  
      
        