  _BASE_CONFIG_ : ./configs/base/sysu.yml
  mode : train
  device : cuda:0
  type : BinaryChangeDetectionFramework
  model_name: ChangeFormer
  logfilepath: logs/changeformer/changeformer_sysu.log
  train:
    epochs : 100
    batch_size : 16
    snapshots_dir : ./checkpoints/
    save_intervals : 1
  eval :
    batch_size : 16
  test:
    batch_size : 16
    checkpoint : checkpoints/ChangeFormer/100.pth
    save_path : ./results/ChangeFormer/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: TransEncoder
      input_nc: 3
      output_nc: 1
      decoder_softmax: False 
      embedding_dim: 256
      embed_dims: [64, 128, 320, 512]
      depths: [3, 3, 4, 3]
    decode_head : 
      type: TransDecoder
      output_nc: 1
      embed_dims: [64, 128, 320, 512]
      depths: [3, 3, 4, 3]
      embedding_dim: 256
      decoder_softmax: False
    feature_interaction:
    prediction_head:


  losses: 
          loss_cls: 
              type: BinaryCrossEntropyLoss
  scheduler: 
          type : ReduceLROnPlateau
          optimizer:  
                type: Adam
                lr: 0.0001
                filter_params: True
                params_rules: {}

  
      
        