  _BASE_CONFIG_ : ./configs/base/levir.yml
  mode : train
  device : GPU
  type : BinaryChangeDetectionFramework
  model_name: BiSRNet
  logfilepath: logs/bisrnet_s2looking/bisrnet_s2looking.log
  train:
    epochs : 5
    batch_size : 4
    snapshots_dir : ./checkpoints/
    save_intervals : 5
  eval :
    batch_size : 10
  test:
    batch_size : 10
    checkpoint : checkpoints/BiSRNet/20.pth
    save_path : ./results/BiSRNet/landslide/
  model:
    CONNECTED: False
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: SemanticReasoningEncoder
    decode_head : 
      type: BiSRNetDecoder
    feature_interaction: 
      type: normal 
      policy: concat
      out_indices: [0,1]
    prediction_head:
  losses: 
          loss_cls: 
              type: BCELoss
  scheduler: 
        type : PolynomialDecayLR
        learning_rate: 0.001
        end_learning_rate: 0.0005
        decay_steps: 4
        power: 0.5
  optimizer:  
        type: Adam
        weight_decay: 0.0005


  
      
        