  _BASE_CONFIG_ : ./configs/base/levir.yml
  mode : train
  device : GPU
  type : BinaryChangeDetectionFramework
  model_name: FC_Siam_conc
  logfilepath: logs/fc_siamconc_levir/fc_siamconc_levir.log
  train:
    epochs : 5
    batch_size : 2
    snapshots_dir : ./checkpoints/FC_Siam_conc/
    save_intervals : 5
  eval :
    batch_size : 4
  test:
    batch_size : 4
    checkpoint : checkpoints/FC_Siam_conc/60.pth
    save_path : ./results/FC_Siam_conc/levir-cd/
  model:
    CONNECTED: True
    CONNECTED_Temporal: T1T2
    type: CDEncoderDecoder
    output_channels: 1
    backbone : 
      type: FCSiamEncoder
      in_channels: 3
      base_channel: 16
    decode_head : 
      type: FCSiamDecoder
      base_channel: 16
      mode : concat
    feature_interaction: 
      type: normal
      policy: concat
      out_indices: [0,1,2,3,4]
    prediction_head:
      
  losses: 
          loss_cls: 
              type: BCELoss
  scheduler: 
        type : PolynomialDecayLR
        learning_rate: 0.001
        end_learning_rate: 0.0005
        decay_steps: 4
        power: 0.5
  optimizer:  
        type: Adam
        weight_decay: 0.0005

      
        